### ISSUE TITLE
train.py不能在CPU上跑

### ISSUE THREAD

**Issue by scottcmm** [bobo0810/Classification#1]
train.py第39行那个应该是规定只能在多张显卡上并行计算
虽然没人会在CPU上跑图像识别吧

**Comment by bobo0810** [comment]
单卡 多卡都支持， 确实没考虑CPU。我明早修复下～😝

**Comment by bobo0810** [comment]
> train.py第39行那个应该是规定只能在多张显卡上并行计算 虽然没人会在CPU上跑图像识别吧

已修复 https://github.com/bobo0810/Classification/commit/de5a2b767121a0a8583c0829278e28f556aea814
